#Total Final Flow - Step 18

SELECT
  year,
  country,
  indication,
  crop_main_group,
  crop_group,
  crop,
  product_type,
  product_group,
  product,
  formulation_type_complete,
  straight_or_mix,
  active_ready_mix,
  distributor_group,
  distributor_original,
  year_calendar,
  active_mix_flexigroup_autumn_spring_herb_emea,
  pest_main_group,
  pest_group,
  complex_pest,
  pest,
  pest_principal,
  area_product_000_ha,
  pest_area_000_ha,
  volume_product_000_kg_li,
  value_distributor_000_eur,
  value_user_000_eur,
  exchange_rate,
  local_currency_code,
  local_currency,
  value_user_000_local,
  value_distributor_000_local,
  report_type,
  completeness_flag,
  formulation_type_code,
  formulation_type,
  cereals_fungicide_segmentation,
  distributor,
  distributor_clean
FROM bcs-edf-ingestion-np.gc_agrowin_cz.fungi_mapping a
LEFT JOIN `bcs-edf-ingestion-np.m_agrowin_cz.distrib_clean` b
ON a.distributor_original = b.distributor
;