#Advanced analytics - Step 41

SELECT
  year,
  country,
  indication,
  crop_main_group,
  crop_group,
  crop,
  area_grown_000_ha,
  area_treated_000_ha,
  area_tractor_000_ha,
  area_product,
  volume_product_000_kg_li,
  value_user_000_eur,
  value_distributor_000_eur,
  exchange_rate,
  local_currency_code,
  local_currency,
  value_user_000_local,
  value_distributor_000_local,
  level,
  dimension,
  r_and_d_vs_generics,
  cereals_fungicide_segmentation,
  crop_main_group_incl_sunflower,
  strategic_crops,
  cluster_new,
  country_group,
  eu_gb_no_ch_VS_non_eu,
  eu27_VS_non_eu,
  fixed_exchange_rate,
  value_user_000_fixed,
  value_distributor_000_fixed,
  "In Season | Only Comparable Data" as report_type_and_completeness
FROM
  `bcs-edf-ingestion.gc_agrowin_cz.ex_rate_clean` ;