SELECT
  yr_nbr as year,
  cntry_nm as country,
  indctn_txt as indication,
  crop_main_grp_cd as crop_main_group,
  crop_grp_cd as crop_group,
  crop_cd as crop,
  prod_typ as product_type,
  prod_grp as product_group,
  prod_cd as product,
  frmla_typ as formulation_type,
  prod_flg_strght_mix as product_flag_straight_mix,
  actv_ready_mix_txt as active_ready_mix,
  distrb_grp as distributor_group,
  distrb_cd as distributor,
  yr_cal as year_calendar,
  actv_mix_autmn_sprng_herb_emea as active_mix_flexigroup_autumn_spring_herb_emea,
  pest_mn_grp as pest_main_group,
  pest_grp as pest_group,
  cmplx_pest as complex_pest,
  pest,
  pest_prncpl as pest_principal,
  area_prod_val as area_product_000_ha,
  pest_area_000_ha,
  vol_prod_000_kg_ltr_val as volume_product_000_kg_li,
  distrb_000_eur_val as value_distributor_000_eur,
  usr_000_eur_val as value_user_000_eur,
  exchg_rt_val as exchange_rate,
  lcl_crncy_cd as local_currency_code,
  lcl_crncy_txt as local_currency,
  usr_000_lcl_val as value_user_000_local,
  distrb_000_lcl_val as value_distributor_000_local
FROM
  `bcs-edf-ingestion.gc_agrowin_cz.cssi_agrwn_full_cycle`