#Total Final Flow - Step 35

SELECT
  year,
  country,
  indication,
  crop_main_group,
  crop_group,
  crop,
  product_type,
  product_group,
  product,
  formulation_type_complete,
  straight_or_mix,
  active_ready_mix,
  distributor_group,
  year_calendar,
  active_mix_flexigroup_autumn_spring_herb_emea,
  pest_main_group,
  pest_group,
  complex_pest,
  pest,
  pest_principal,
  exchange_rate,
  local_currency_code,
  local_currency,
  report_type,
  completeness_flag,
  formulation_type_code,
  formulation_type,
  cereals_fungicide_segmentation,
  --distributor,
  cluster_new,
  country_group,
  eu_gb_no_ch_VS_non_eu,
  eu27_VS_non_eu,
  r_and_d_vs_generics,
  crop_main_group_incl_sunflower,
  strategic_crops,
  fixed_exchange_rate,
  budget,
  CURRENT_TIMESTAMP() AS last_update_date,
  IF(distributor_clean IS NOT NULL,distributor_clean,distributor_original) AS distributor,
  CONCAT(report_type," | ",completeness_flag) AS report_type_and_completeness,
  (value_user_000_local * 1000) AS value_user_local,
  (value_distributor_000_local * 1000) AS value_distributor_local,
  (value_user_000_eur * 1000) AS value_user_eur,
  (value_distributor_000_eur * 1000) AS value_distributor_eur,
  ((value_distributor_000_local*1000)/fixed_exchange_rate) AS value_distributor_fixed,
  ((value_user_000_local*1000)/fixed_exchange_rate) AS value_user_fixed,
  (area_product_000_ha * 1000) AS area_product_ha,
  (volume_product_000_kg_li * 1000) AS volume_product_kg_li,
  (pest_area_000_ha * 1000) AS pest_area_ha,
  CASE
    WHEN report_type ="Full-Cycle" THEN "Full-Cycle"
    WHEN year = year_calendar THEN "Spring"
    WHEN year != year_calendar THEN "Autumn"
  END AS spring_or_autumn,
  'A' AS action_type,
  CURRENT_TIMESTAMP() AS row_insert_timestamp,
  CURRENT_TIMESTAMP() AS row_update_timestamp
FROM
  `bcs-edf-ingestion-np.gc_agrowin_cz.exchange_rate_mapping`;